// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutUsDocumentDataSlicesSlice = WrapperSectionSlice;

/**
 * Content for About Us documents
 */
interface AboutUsDocumentData {
  /**
   * Slice Zone field in *About Us*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutUsDocumentDataSlicesSlice> /**
   * Meta Description field in *About Us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about_us.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About Us*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *About Us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about_us.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * About Us document from Prismic
 *
 * - **API ID**: `about_us`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutUsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AboutUsDocumentData>,
    "about_us",
    Lang
  >;

type BlogDocumentDataSlicesSlice = never;

/**
 * Content for blog documents
 */
interface BlogDocumentData {
  /**
   * Slice Zone field in *blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Description field in *blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

interface HeaderDocumentData {}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type PagesDocumentDataSlicesSlice =
  | FancyShortBannerSectionSlice
  | WrapperSectionSlice
  | FeedbackSectionSlice
  | FeatureTwoSectionSlice
  | ServiceBoxSlice
  | FeatureOneSectionSlice
  | HeroSlice;

/**
 * Content for pages documents
 */
interface PagesDocumentData {
  /**
   * Slice Zone field in *pages*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: pages.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PagesDocumentDataSlicesSlice> /**
   * Meta Description field in *pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: pages.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *pages*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pages.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: pages.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * pages document from Prismic
 *
 * - **API ID**: `pages`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PagesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PagesDocumentData>, "pages", Lang>;

type ProjectsDocumentDataSlicesSlice = never;

/**
 * Content for projects documents
 */
interface ProjectsDocumentData {
  /**
   * Slice Zone field in *projects*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectsDocumentDataSlicesSlice> /**
   * Meta Description field in *projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: projects.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: projects.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectsDocumentData>,
    "projects",
    Lang
  >;

type ServicesDocumentDataSlicesSlice = never;

/**
 * Content for Services documents
 */
interface ServicesDocumentData {
  /**
   * Slice Zone field in *Services*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: services.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServicesDocumentDataSlicesSlice> /**
   * Meta Description field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: services.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: services.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Services document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServicesDocumentData>,
    "services",
    Lang
  >;

export type AllDocumentTypes =
  | AboutUsDocument
  | BlogDocument
  | HeaderDocument
  | PagesDocument
  | ProjectsDocument
  | ServicesDocument;

/**
 * Primary content in *FancyShortBannerSection → Primary*
 */
export interface FancyShortBannerSectionSliceDefaultPrimary {
  /**
   * Top Text field in *FancyShortBannerSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fancy_short_banner_section.primary.top_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_text: prismic.RichTextField;

  /**
   * Title field in *FancyShortBannerSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fancy_short_banner_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for FancyShortBannerSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FancyShortBannerSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FancyShortBannerSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FancyShortBannerSection*
 */
type FancyShortBannerSectionSliceVariation =
  FancyShortBannerSectionSliceDefault;

/**
 * FancyShortBannerSection Shared Slice
 *
 * - **API ID**: `fancy_short_banner_section`
 * - **Description**: FancyShortBannerSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FancyShortBannerSectionSlice = prismic.SharedSlice<
  "fancy_short_banner_section",
  FancyShortBannerSectionSliceVariation
>;

/**
 * Primary content in *FeatureOneSection → Primary*
 */
export interface FeatureOneSectionSliceDefaultPrimary {
  /**
   * Title field in *FeatureOneSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_one_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sub Title field in *FeatureOneSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_one_section.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;
}

/**
 * Default variation for FeatureOneSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureOneSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureOneSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeatureOneSection*
 */
type FeatureOneSectionSliceVariation = FeatureOneSectionSliceDefault;

/**
 * FeatureOneSection Shared Slice
 *
 * - **API ID**: `feature_one_section`
 * - **Description**: FeatureOneSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureOneSectionSlice = prismic.SharedSlice<
  "feature_one_section",
  FeatureOneSectionSliceVariation
>;

/**
 * Primary content in *FeatureTwoSection → Primary*
 */
export interface FeatureTwoSectionSliceDefaultPrimary {
  /**
   * Image field in *FeatureTwoSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_two_section.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Top Text field in *FeatureTwoSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_two_section.primary.top_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_text: prismic.RichTextField;

  /**
   * Title field in *FeatureTwoSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_two_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *FeatureTwoSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_two_section.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Card One Name field in *FeatureTwoSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_two_section.primary.card_one_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  card_one_name: prismic.RichTextField;

  /**
   * Card One Text field in *FeatureTwoSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_two_section.primary.card_one_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  card_one_text: prismic.RichTextField;

  /**
   * icon field in *FeatureTwoSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_two_section.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * More Btn Link field in *FeatureTwoSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_two_section.primary.more_btn_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  more_btn_link: prismic.LinkField;

  /**
   * More Btn Label field in *FeatureTwoSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_two_section.primary.more_btn_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  more_btn_label: prismic.KeyTextField;
}

/**
 * Primary content in *FeatureTwoSection → Items*
 */
export interface FeatureTwoSectionSliceDefaultItem {
  /**
   * Text List field in *FeatureTwoSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_two_section.items[].text_list
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_list: prismic.RichTextField;
}

/**
 * Default variation for FeatureTwoSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureTwoSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureTwoSectionSliceDefaultPrimary>,
  Simplify<FeatureTwoSectionSliceDefaultItem>
>;

/**
 * Primary content in *FeatureTwoSection → Primary*
 */
export interface FeatureTwoSectionSliceFeatureTwoWithNamePrimary {
  /**
   * Image field in *FeatureTwoSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_two_section.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *FeatureTwoSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_two_section.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Title field in *FeatureTwoSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_two_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sub Title field in *FeatureTwoSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_two_section.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;

  /**
   * Card One Name field in *FeatureTwoSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_two_section.primary.card_one_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  card_one_name: prismic.RichTextField;

  /**
   * Card One Text field in *FeatureTwoSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_two_section.primary.card_one_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  card_one_text: prismic.RichTextField;

  /**
   * icon field in *FeatureTwoSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_two_section.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Feature Two With Name variation for FeatureTwoSection Slice
 *
 * - **API ID**: `featureTwoWithName`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureTwoSectionSliceFeatureTwoWithName =
  prismic.SharedSliceVariation<
    "featureTwoWithName",
    Simplify<FeatureTwoSectionSliceFeatureTwoWithNamePrimary>,
    never
  >;

/**
 * Slice variation for *FeatureTwoSection*
 */
type FeatureTwoSectionSliceVariation =
  | FeatureTwoSectionSliceDefault
  | FeatureTwoSectionSliceFeatureTwoWithName;

/**
 * FeatureTwoSection Shared Slice
 *
 * - **API ID**: `feature_two_section`
 * - **Description**: FeatureTwoSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureTwoSectionSlice = prismic.SharedSlice<
  "feature_two_section",
  FeatureTwoSectionSliceVariation
>;

/**
 * Primary content in *FeedbackSection → Primary*
 */
export interface FeedbackSectionSliceDefaultPrimary {
  /**
   * Title field in *FeedbackSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feedback_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *FeedbackSection → Items*
 */
export interface FeedbackSectionSliceDefaultItem {
  /**
   * Feedback Title field in *FeedbackSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feedback_section.items[].feedback_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feedback_title: prismic.RichTextField;

  /**
   * Feedback Description field in *FeedbackSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feedback_section.items[].feedback_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feedback_description: prismic.RichTextField;

  /**
   * Feedback Name field in *FeedbackSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feedback_section.items[].feedback_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feedback_name: prismic.RichTextField;

  /**
   * Feedback Image field in *FeedbackSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feedback_section.items[].feedback_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  feedback_image: prismic.ImageField<never>;
}

/**
 * Default variation for FeedbackSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeedbackSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeedbackSectionSliceDefaultPrimary>,
  Simplify<FeedbackSectionSliceDefaultItem>
>;

/**
 * Slice variation for *FeedbackSection*
 */
type FeedbackSectionSliceVariation = FeedbackSectionSliceDefault;

/**
 * FeedbackSection Shared Slice
 *
 * - **API ID**: `feedback_section`
 * - **Description**: FeedbackSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeedbackSectionSlice = prismic.SharedSlice<
  "feedback_section",
  FeedbackSectionSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sub Title field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;

  /**
   * image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Footer Text field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.footer_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  footer_text: prismic.RichTextField;

  /**
   * Bottom text field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.bottom_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bottom_text: prismic.RichTextField;

  /**
   * Card One Text field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.card_one_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  card_one_text: prismic.RichTextField;

  /**
   * Card One Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.card_one_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  card_one_link: prismic.LinkField;

  /**
   * Card One Label field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.card_one_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_one_label: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ServiceBox → Items*
 */
export interface ServiceBoxSliceDefaultItem {
  /**
   * Icon field in *ServiceBox → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_box.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *ServiceBox → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_box.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ServiceBox → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_box.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * link field in *ServiceBox → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service_box.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Background Color field in *ServiceBox → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_box.items[].background_color
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  background_color: prismic.KeyTextField;
}

/**
 * Default variation for ServiceBox Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceBoxSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ServiceBoxSliceDefaultItem>
>;

/**
 * Primary content in *ServiceBox → Items*
 */
export interface ServiceBoxSliceFeaturesWrapperItem {
  /**
   * Icon field in *ServiceBox → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_box.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *ServiceBox → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_box.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ServiceBox → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_box.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Delay field in *ServiceBox → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: service_box.items[].delay
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  delay: prismic.NumberField;
}

/**
 * Features Wrapper variation for ServiceBox Slice
 *
 * - **API ID**: `featuresWrapper`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceBoxSliceFeaturesWrapper = prismic.SharedSliceVariation<
  "featuresWrapper",
  Record<string, never>,
  Simplify<ServiceBoxSliceFeaturesWrapperItem>
>;

/**
 * Primary content in *ServiceBox → Primary*
 */
export interface ServiceBoxSliceBlogSectionOnePrimary {
  /**
   * Title field in *ServiceBox → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_box.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Button Link field in *ServiceBox → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service_box.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Label field in *ServiceBox → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_box.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;
}

/**
 * Primary content in *ServiceBox → Items*
 */
export interface ServiceBoxSliceBlogSectionOneItem {
  /**
   * Image field in *ServiceBox → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_box.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Badge field in *ServiceBox → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_box.items[].badge
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  badge: prismic.RichTextField;

  /**
   * link field in *ServiceBox → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service_box.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Blog Title field in *ServiceBox → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_box.items[].blog_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  blog_title: prismic.RichTextField;

  /**
   * Badge Bg Color field in *ServiceBox → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_box.items[].badge_bg_color
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  badge_bg_color: prismic.KeyTextField;
}

/**
 * Blog Section One variation for ServiceBox Slice
 *
 * - **API ID**: `blogSectionOne`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceBoxSliceBlogSectionOne = prismic.SharedSliceVariation<
  "blogSectionOne",
  Simplify<ServiceBoxSliceBlogSectionOnePrimary>,
  Simplify<ServiceBoxSliceBlogSectionOneItem>
>;

/**
 * Slice variation for *ServiceBox*
 */
type ServiceBoxSliceVariation =
  | ServiceBoxSliceDefault
  | ServiceBoxSliceFeaturesWrapper
  | ServiceBoxSliceBlogSectionOne;

/**
 * ServiceBox Shared Slice
 *
 * - **API ID**: `service_box`
 * - **Description**: ServiceBox
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceBoxSlice = prismic.SharedSlice<
  "service_box",
  ServiceBoxSliceVariation
>;

/**
 * Primary content in *WrapperSection → Primary*
 */
export interface WrapperSectionSliceDefaultPrimary {
  /**
   * Title field in *WrapperSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: wrapper_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sub Title field in *WrapperSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: wrapper_section.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;

  /**
   * Button Link field in *WrapperSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: wrapper_section.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Label field in *WrapperSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: wrapper_section.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;
}

/**
 * Default variation for WrapperSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WrapperSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WrapperSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *WrapperSection → Primary*
 */
export interface WrapperSectionSliceHeroBannerPrimary {
  /**
   * Title field in *WrapperSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: wrapper_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sub Title field in *WrapperSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: wrapper_section.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;
}

/**
 * Hero Banner variation for WrapperSection Slice
 *
 * - **API ID**: `heroBanner`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WrapperSectionSliceHeroBanner = prismic.SharedSliceVariation<
  "heroBanner",
  Simplify<WrapperSectionSliceHeroBannerPrimary>,
  never
>;

/**
 * Slice variation for *WrapperSection*
 */
type WrapperSectionSliceVariation =
  | WrapperSectionSliceDefault
  | WrapperSectionSliceHeroBanner;

/**
 * WrapperSection Shared Slice
 *
 * - **API ID**: `wrapper_section`
 * - **Description**: WrapperSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WrapperSectionSlice = prismic.SharedSlice<
  "wrapper_section",
  WrapperSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutUsDocument,
      AboutUsDocumentData,
      AboutUsDocumentDataSlicesSlice,
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      HeaderDocument,
      HeaderDocumentData,
      PagesDocument,
      PagesDocumentData,
      PagesDocumentDataSlicesSlice,
      ProjectsDocument,
      ProjectsDocumentData,
      ProjectsDocumentDataSlicesSlice,
      ServicesDocument,
      ServicesDocumentData,
      ServicesDocumentDataSlicesSlice,
      AllDocumentTypes,
      FancyShortBannerSectionSlice,
      FancyShortBannerSectionSliceDefaultPrimary,
      FancyShortBannerSectionSliceVariation,
      FancyShortBannerSectionSliceDefault,
      FeatureOneSectionSlice,
      FeatureOneSectionSliceDefaultPrimary,
      FeatureOneSectionSliceVariation,
      FeatureOneSectionSliceDefault,
      FeatureTwoSectionSlice,
      FeatureTwoSectionSliceDefaultPrimary,
      FeatureTwoSectionSliceDefaultItem,
      FeatureTwoSectionSliceFeatureTwoWithNamePrimary,
      FeatureTwoSectionSliceVariation,
      FeatureTwoSectionSliceDefault,
      FeatureTwoSectionSliceFeatureTwoWithName,
      FeedbackSectionSlice,
      FeedbackSectionSliceDefaultPrimary,
      FeedbackSectionSliceDefaultItem,
      FeedbackSectionSliceVariation,
      FeedbackSectionSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ServiceBoxSlice,
      ServiceBoxSliceDefaultItem,
      ServiceBoxSliceFeaturesWrapperItem,
      ServiceBoxSliceBlogSectionOnePrimary,
      ServiceBoxSliceBlogSectionOneItem,
      ServiceBoxSliceVariation,
      ServiceBoxSliceDefault,
      ServiceBoxSliceFeaturesWrapper,
      ServiceBoxSliceBlogSectionOne,
      WrapperSectionSlice,
      WrapperSectionSliceDefaultPrimary,
      WrapperSectionSliceHeroBannerPrimary,
      WrapperSectionSliceVariation,
      WrapperSectionSliceDefault,
      WrapperSectionSliceHeroBanner,
    };
  }
}
