// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  column_text_section: dynamic(() => import("./ColumnTextSection")),
  contact_address: dynamic(() => import("./ContactAddress")),
  counter_two_section: dynamic(() => import("./CounterTwoSection")),
  fancy_short_banner_section: dynamic(
    () => import("./FancyShortBannerSection"),
  ),
  feature_one_section: dynamic(() => import("./FeatureOneSection")),
  feature_two_section: dynamic(() => import("./FeatureTwoSection")),
  feedback_section: dynamic(() => import("./FeedbackSection")),
  hero: dynamic(() => import("./Hero")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  portfolio_category_section: dynamic(
    () => import("./PortfolioCategorySection"),
  ),
  service_box: dynamic(() => import("./ServiceBox")),
  testimonial_feedback_section: dynamic(
    () => import("./TestimonialFeedbackSection"),
  ),
  testimonial_feedback_two: dynamic(() => import("./TestimonialFeedbackTwo")),
  wrapper_section: dynamic(() => import("./WrapperSection")),
};
